name: CI wowkflow

on: [push, pull_request]

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with dev
      - name: Lint and format check
        run: |
          black --check --diff .
          flake8 --show-source .
          isort --check-only --diff .
          mypy --show-column-numbers --show-error-context .
        continue-on-error: true
      - name: Test with pytest and doctest
        run: |
          pytest --cov --doctest-modules .
      - name: Upload coverge reports to Codecov via GitHub Actions
        uses: codecov/codecov-action@v3
